# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: Seznam článků
    title: Podívejte se na naše články
    link: entries
  - label: O redakci
    link: pages/o-redakci
  - label: Autoři
    link: people


